### ISSUE TITLE
视频规则更新后B站的 换一换 点击没反应了

### ISSUE THREAD

**Issue by smdx** [xinggsf/Adblock-Plus-Rule#105]
大佬好，视频规则更新后B站推荐视频那个 换一换 点击没反应了

**Comment by kano-luna** [comment]
不是换一换失效了，你注意看，其实两排的个性化推荐被杀掉了，不知道这啥情况，同配置chrome反而没这问题

**Comment by RealManShao** [comment]
实测最新版已经修复了

**Comment by smdx** [comment]
> 实测最新版已经修复了

确实可以了，谢谢告知
