### ISSUE TITLE
Inactive Domains

### ISSUE THREAD

**Issue by sr093906** [xinggsf/Adblock-Plus-Rule#37]
Following entries have no DNS records.

afp.chinanews.com  
atm.youku.com  
aty.sohu.com  
cbjslog.baidu.com  
cgm.shicimingju.com  
coinhive-manager.com 
games.ifeng.com  
hdad.baike.com  
img2.126.net  
iwanad.baidu.com  
orz.hupu.com 
spcode.baidu.com  
statics.3987.com  
tajs.qq.com  
taobao.qq.com  
tcss.qq.com  
uniondm.cz88.net  
wangyou.pcgames.com.cn  
www.you85.com  
100.admin5.com

**Comment by xinggsf** [comment]
Thank you! How test you?
