### ISSUE TITLE
binance.com [Incorrect Blocking]

### ISSUE THREAD

**Issue by slavaleleka** [xinggsf/Adblock-Plus-Rule#52]
P2P trading on binance.com is blocked by
`||p2p.$xmlhttprequest,websocket,ping,domain=~huya.com`

could you please improve it to 
`||p2p.$xmlhttprequest,websocket,ping,domain=~huya.com|~binance.com`

check on [p2p.binance.com](https://p2p.binance.com/)

**Comment by xinggsf** [comment]
fix it
