### ISSUE TITLE
乘风通用&视频&小众视频过滤规则 误杀

### ISSUE THREAD

**Issue by Franinc** [xinggsf/Adblock-Plus-Rule#55]
视频规则 157行 `|https://$script,subdocument,popup,3p,domain=btsow.bar|dandanzan10.top|nunuyy2.org|rarbgprx.org` 把rarbg验证码页面的`https://dyncdn.me/static/20/js/jquery-1.11.3.min.js`ban了 导致无法输入验证码
测试链接 https://rarbgprx.org/threat_defence.php

通用规则 68行 `*/ad-` 把非广告脚本ban了 导致xbox网站右上角无法点登录 登录按钮边的头像也失踪了
测试链接 https://www.xbox.com/en-US/xbox-game-pass/pc-game-pass

小众视频规则 122行 `azureedge.net` 把css ban了 例如https://answers.microsoft.com/  丢失css

**Comment by xinggsf** [comment]
update rule!
