### ISSUE TITLE
yiche.com [Incorrect blocking]

### ISSUE THREAD

**Issue by Alex-302** [xinggsf/Adblock-Plus-Rule#57]
### Issue URL (Incorrect Blocking)
 [https://www.yiche.com/](https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=https%3A%2F%2Fwww.yiche.com%2F)
### Comment
> 在开启广告过滤器后，广告可以被过滤，但正常图片不能加载

Caused by `d2.yiche.com`

### Screenshots
<details>
  <summary>Screenshot 1</summary>

  ![Screenshot 1](https://reports-img.adguard.com/AC42Jod.jpg)
</details>
<details>
  <summary>Screenshot 2</summary>

  ![Screenshot 2](https://reports-img.adguard.com/o9lWQ2M.jpg)
</details>

### System configuration

Information | value
--- | ---
AdGuard product: | AdGuard for Windows v7.10 nightly 17
Browser: | Edge 103.0.1264.37 (Chromium-based)
AdGuard driver: | WFP
Stealth mode: | disabled
DNS filtering: | disabled
Filters: | <b>Ad Blocking:</b><br/>EasyList, <br/>Peter Lowe's Blocklist, <br/>AdGuard Mobile Ads, <br/>AdGuard Base<br/><br/><b>Privacy:</b><br/>EasyPrivacy, <br/>Fanboy's Enhanced Tracking List, <br/>Fanboy's Anti-Facebook List, <br/>Fanboy's Anti-thirdparty Fonts, <br/>Legitimate URL Shortener, <br/>AdGuard URL Tracking, <br/>AdGuard Tracking Protection<br/><br/><b>Social Widgets:</b><br/>Fanboy's Social Blocking List, <br/>AdGuard Social Media<br/><br/><b>Annoyances:</b><br/>Fanboy's Annoyances, <br/>Web Annoyances Ultralist, <br/>Adblock Warning Removal List, <br/>I don't care about cookies, <br/>EasyList Cookie List, <br/>Dandelion Sprout's Annoyances List, <br/>AdGuard Annoyances<br/><br/><b>Security:</b><br/>Online Malicious URL Blocklist, <br/>NoCoin Filter List<br/><br/><b>Other:</b><br/>AdGuard Experimental<br/><br/><b>Language-specific:</b><br/>EasyList China, <br/>ChinaList+EasyList, <br/>xinggsf, <br/>AdGuard Chinese
Userscripts: | https://userscripts.adtidy.org/beta/assistant/4.3/assistant.user.js,<br>https://userscripts.adtidy.org/beta/adguard-extra/1.0/adguard-extra.user.js,<br>https://userscripts.adtidy.org/beta/popup-blocker/2.5/popupblocker.user.js

**Comment by xinggsf** [comment]
fix it
