### ISSUE TITLE
youtube.com [incorrect blocking]

### ISSUE THREAD

**Issue by mikewy0527** [xinggsf/Adblock-Plus-Rule#60]
Yestoday, I found the `youtube.com` page cannot be load normally, cause by following rule in file `rule.txt`:
```
*/ad3$script
```

maybe the the reason was youtube use the urls `https://www.youtube.com/s/desktop/ad3ffe7b/*/*.js`,  `ad3ffe7b` lead to match the rule `*ad3$script`

A workaround is add the following rule before rule `*/ad3$script` 
```
@@||www.youtube.com/s/desktop/ad3$script
```

**Comment by xxh0823** [comment]
出现了同样问题，烦请作者修复。

**Comment by podipod** [comment]
同样问题

**Comment by th3weird0** [comment]
+1 开了mv.txt和rule.txt youtube就打不开了

**Comment by xinggsf** [comment]
fix it!
