### ISSUE TITLE
2022.9.24开启该规则后，知乎专栏正文内容消失，评论内容消失

### ISSUE THREAD

**Issue by RTX10086** [xinggsf/Adblock-Plus-Rule#64]
问题100%复现于任何https://zhuanlan.zhihu.com

开启本规则后，问题出现；关闭后，问题解决

由此可判定时该规则有问题

使用工具：AdGuard MS Edge插件
测试网址：https://zhuanlan.zhihu.com/p/347132218

开启时：
<img width="716" alt="Snipaste_2022-09-24_17-34-05" src="https://user-images.githubusercontent.com/46842736/192108964-244bef66-0fa5-4011-98a7-3e14f3947cdb.png">

关闭后：
<img width="726" alt="Snipaste_2022-09-24_17-34-24" src="https://user-images.githubusercontent.com/46842736/192108971-ef10241c-b30d-4937-b578-8114560a1f25.png">

**Comment by xinggsf** [comment]
已经解决了，更新规则即可
