### ISSUE TITLE
rule.txt误杀夸克网盘

### ISSUE THREAD

**Issue by tanghengvip** [xinggsf/Adblock-Plus-Rule#65]
adguard home发现误杀夸克网盘地址：
pan.quark.cn
drive.quark.cn
![image](https://user-images.githubusercontent.com/4047349/194708421-696ed4ea-f271-455a-9b65-daa30c96a405.png)
但是在rules.txt中没有搜到这两个域名，是我姿势不对吗？

**Comment by xinggsf** [comment]
应该是ADG的问题
