### ISSUE TITLE
误杀反馈：拦截 stripe.com 导致 nextdns 会员购买页面崩溃

### ISSUE THREAD

**Issue by xiaorong61** [xinggsf/Adblock-Plus-Rule#67]
https://my.nextdns.io/account

<img width="922" alt="image" src="https://user-images.githubusercontent.com/5251387/210931522-848b5bb7-da8a-4108-8719-8b1cb0d06c08.png">

![image](https://user-images.githubusercontent.com/5251387/211130922-ca022880-cc09-497a-a1ef-018c04812716.png)

**Comment by xinggsf** [comment]
感谢反馈！无帐号，请更新后测试再反馈

**Comment by xiaorong61** [comment]
测试没问题了，谢谢。
