### ISSUE TITLE
电视上的云视听极光的广告抓包数据

### ISSUE THREAD

**Issue by lon91ong** [xinggsf/Adblock-Plus-Rule#68]
通过[路由器抓包](https://www.jianshu.com/p/7fcf12ce4474)得到广告的链接如下：
```
http://sv-video.play.t002.ottcn.com/playlist.m3u8?vids=w3715yeyz3p|w3728l84yj1&sdtfrom_list=v8256|v8256&speed=&dtype=1&defn=&platform=
```
用浏览器打开链接下载得到`playlist.m3u8`文件，内容如下图所示：
![playlist.m3u8](https://user-images.githubusercontent.com/16462258/212539290-dff41a9a-635d-4507-8086-8a7fab8b2529.png)

广告链接形如`http://203.205.137.89/defaultts.tc.qq.com/...`这种格式，不同的广告前面的ip会变
在现有的乘风规则没有搜到`defaultts.tc.qq.com`相关内容，倒是lean的adbyby规则中有, 但不知为啥没有效果

试着将域名`sv-video.play.t002.ottcn.com`重定向到`127.0.0.1`测试，广告依旧! 继续分析抓包数据，发现下面一条：
`http://182.254.116.116/d?dn=sv-video.play.t002.ottcn.com&ttl=1`
这是用HTTP跳过了本地设置的DNS服务器，发现还有几条类似的httpdns请求数据，内容与播放正常视频相关
所以不能把`182.254.116.116`加入黑名单
![抓包截图](https://user-images.githubusercontent.com/16462258/212539919-810e2738-6f25-4c00-834d-a7d24e286967.png)

怎样能阻止httpdns解析指定域名`sv-video.play.t002.ottcn.com`呢？

**Comment by xinggsf** [comment]
在路由端装clash,可屏蔽指定域名和FQ上网

**Comment by lon91ong** [comment]
> 在路由端装clash,可屏蔽指定域名和FQ上网

不只是屏蔽域名，还要屏蔽httpdns解析该域名，不能屏蔽httpdns解析服务器，别的有用域名还要用
